Revisión de Templates
ropensci/software-review pull request #582
Opened 2023-03-19 19:47 UTC by paocorrales

@yabellini all 4 templates are included in this PR, enjoy!

2023-03-19 20:03 UTC, yabellini commented
Thanks!!

2023-03-20 11:58 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- Por favor, indica qué categoría(s) aplica(n) a este paquete. Las puedes encontrar en nuestras [políticas de inclusión de paquetes](https://devdevguide.netlify.app/es/softwarereview_policies.es.html
Posiblemente esta url cambie.

2023-03-20 11:59 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- ¿Hay otros paquetes de R que logren el mismo objetivo? Si los hay, ¿cómo se diferencian del tuyo, o alcanzan nuestro [criterio del mejor de su categoría](https://devdevguide.netlify.app/es/software
Mismo comentario que el anterio.

2023-03-20 12:09 UTC, yabellini approved these changes
Some questions.

2023-03-20 12:09 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +-   (Si aplica) Explique las razones por las cuales el paqute no satisface alguno de los [chequeos de `pkgcheck`](https://docs.ropensci.org/pkgcheck/).
```suggestion
-   (Si aplica) Explica las razones por las cuales el paquete no satisface alguno de los [chequeos de `pkgcheck`](https://docs.ropensci.org/pkgcheck/).
```

2023-03-20 12:10 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- Por favor, indica qué categoría(s) aplica(n) a este paquete. Las puedes encontrar en nuestras [políticas de inclusión de paquetes](https://devdevguide.netlify.app/es/softwarereview_policies.es.html
Las cambiamos todas juntas si es que cambia.

2023-03-20 12:10 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- ¿Hay otros paquetes de R que logren el mismo objetivo? Si los hay, ¿cómo se diferencian del tuyo, o alcanzan nuestro [criterio del mejor de su categoría](https://devdevguide.netlify.app/es/software
Las cambiamos todas juntas si es que cambia.

2023-03-20 13:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/E-proponer-software-para-revision.md
> +	- [ ] datos de texto (text data)
@maelle alguna opinión sobre esto?

2023-03-31 06:08 UTC, maelle commented on .github/ISSUE_TEMPLATE/E-proponer-software-para-revision.md
> +	- [ ] datos de texto (text data)
I've opened https://github.com/ropensci/dev_guide/issues/648, excellent catch, muchas gracias!

2024-08-15 16:55 UTC, yabellini commented
@mpadge @maelle can I merge this PR?

2024-08-16 08:27 UTC, mpadge requested changes
Thanks @yabellini for not losing sight of this important PR! Yes, you can merge it, but with one change of removing template G for stats, because we currently have no actual ability to handle Spanish stats submissions. Could you please remove from this PR, merge the rest, and then open another one with just that template from an internal branch of this repo? Then we'll have the template ready to go once we have developed that far. Thanks!

2024-08-16 19:38 UTC, yabellini approved these changes
Updating the links to the Spanish version of the book.

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- Por favor, indica qué categoría(s) aplica(n) a este paquete. Las puedes encontrar en nuestras [políticas de inclusión de paquetes](https://devdevguide.netlify.app/es/softwarereview_policies.es.html
```suggestion
- Por favor, indica qué categoría(s) aplica(n) a este paquete. Las puedes encontrar en nuestras [políticas de inclusión de paquetes](https://devguide.ropensci.org/es/softwarereview_policies.es.html#package-categories). Por favor, tilda todas las apropiadas. Si tienes dudas, te sugerimos que comiences un pre-envío.
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- ¿Hay otros paquetes de R que logren el mismo objetivo? Si los hay, ¿cómo se diferencian del tuyo, o alcanzan nuestro [criterio del mejor de su categoría](https://devdevguide.netlify.app/es/software
```suggestion
- ¿Hay otros paquetes de R que logren el mismo objetivo? Si los hay, ¿cómo se diferencian del tuyo, o alcanzan nuestro [criterio del mejor de su categoría](https://devguide.ropensci.org/es/softwarereview_policies.es.html#overlap)?
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +-   (Si aplica) ¿Tu paquete cumple con nuestras [guías de _Ética, Privacidad de Datos e Investigación con Sujetos Humanos_](https://devdevguide.netlify.app/es/softwarereview_policies.es.html#%C3%A9ti
```suggestion
-   (Si aplica) ¿Tu paquete cumple con nuestras [guías de _Ética, Privacidad de Datos e Investigación con Sujetos Humanos_](https://devguide.ropensci.org/es/softwarereview_policies.es.html#ethics-data-privacy-and-human-subjects-research)?
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] He leído la [guía de empaquetado de rOpenSci](https://devdevguide.netlify.app/es/pkg_building.es.html).
```suggestion
- [ ] He leído la [guía de empaquetado de rOpenSci](https://devguide.ropensci.org/es/pkg_building.es.html).
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] He leído la [guía de autoría](https://devdevguide.netlify.app/es/softwarereview_author.es.html) y pienso mantener este paquete durante al menos 2 años o encontrar un reemplazo.
```suggestion
- [ ] He leído la [guía de autoría](https://devguide.ropensci.org/es/softwarereview_author.es.html) y pienso mantener este paquete durante al menos 2 años o encontrar un reemplazo.
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] Contiene un [archivo README con instrucciones para instalar la versión de desarrollo](https://devdevguide.netlify.app/es/pkg_building.es.html#readme).
```suggestion
- [ ] Contiene un [archivo README con instrucciones para instalar la versión de desarrollo](https://devguide.ropensci.org/es/pkg_building.es.html#readme).
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] Incluye [documentación con ejemplos para todas las funciones, creada con roxygen2](https://devdevguide.netlify.app/es/pkg_building.es.html#documentaci%C3%B3n).
```suggestion
- [ ] Incluye [documentación con ejemplos para todas las funciones, creada con roxygen2](https://devguide.ropensci.org/es/pkg_building.es.html#documentation).
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] Tiene una [suite de tests](https://devdevguide.netlify.app/es/pkg_building.es.html#testeo).
```suggestion
- [ ] Tiene una [suite de tests](https://devguide.ropensci.org/es/pkg_building.es.html#testing).
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] Tiene [integración contínua](https://devdevguide.netlify.app/es/pkg_ci.es.html), incluyendo reporte de cobertura de tests.
```suggestion
- [ ] Tiene [integración contínua](https://devguide.ropensci.org/es/pkg_ci.es.html), incluyendo reporte de cobertura de tests.
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/D-enviar-software-para-revision.md
> +- [ ] Estoy de acuerdo en cumplir el [Código de Conducta de rOpenSci](https://devdevguide.netlify.app/es/softwarereview_policies.es.html#code-of-conduct) durante el proceso de revisión, y en mantener
```suggestion
- [ ] Estoy de acuerdo en cumplir el [Código de Conducta de rOpenSci](https://devguide.ropensci.org//es/softwarereview_policies.es.html#code-of-conduct) durante el proceso de revisión, y en mantener mi paquete si éste es aceptado.
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/E-proponer-software-para-revision.md
> +- Por favor, indica qué categoría(s) aplica(n) a este paquete. Las puedes encontrar en nuestras [políticas de inclusión de paquetes](https://devdevguide.netlify.app/es/softwarereview_policies.es.html
```suggestion
- Por favor, indica qué categoría(s) aplica(n) a este paquete. Las puedes encontrar en nuestras [políticas de inclusión de paquetes](https://devguide.ropensci.org/es/softwarereview_policies.es.html#package-categories) y [categorías de paquetes estadistico (Inglés)](https://stats-devguide.ropensci.org/overview.html#overview-categories). Por favor, tilda todas las apropiadas.
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/E-proponer-software-para-revision.md
> +- ¿Hay otros paquetes de R que logren el mismo objetivo? Si los hay, ¿cómo se diferencian del tuyo, o alcanzan nuestro [criterio del mejor de su categoría](https://devdevguide.netlify.app/es/software
```suggestion
- ¿Hay otros paquetes de R que logren el mismo objetivo? Si los hay, ¿cómo se diferencian del tuyo, o alcanzan nuestro [criterio del mejor de su categoría](https://devguide.ropensci.org/es/softwarereview_policies.es.html#overlap)?
```

2024-08-16 19:38 UTC, yabellini commented on .github/ISSUE_TEMPLATE/E-proponer-software-para-revision.md
> +-   (Si aplica) ¿Tu paquete cumple con nuestras [guías de _Ética, Privacidad de Datos e Investigación con Sujetos Humanos_](https://devdevguide.netlify.app/es/softwarereview_policies.es.html#%C3%A9ti
```suggestion
-   (Si aplica) ¿Tu paquete cumple con nuestras [guías de _Ética, Privacidad de Datos e Investigación con Sujetos Humanos_](https://devguide.ropensci.org/es/softwarereview_policies.es.html#ethics-data-privacy-and-human-subjects-research)?
```

2024-08-16 19:43 UTC, merged